from .combining_technique import Centroid, Sum
from .embedding_technique import WordEmbeddingTechnique, SentenceEmbeddingTechnique, DocumentEmbeddingTechnique, \
    FromWordsSentenceEmbeddingTechnique, FromSentencesDocumentEmbeddingTechnique, FromWordsDocumentEmbeddingTechnique
